name: monet2_configuration
description: "A configuration app for the Monet2 theming engine."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  material_symbols_icons: ^4.2815.1
  settings_tiles: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: FlexFontEn
      fonts:
        - asset: assets/fonts/flex-Regular.ttf
          weight: 400
        - asset: assets/fonts/flex-Medium.ttf
          weight: 500
        - asset: assets/fonts/flex-Medium.ttf
          weight: 600
        - asset: assets/fonts/flex-Bold.ttf
          weight: 700
